spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/dby_shop?useUnicode=true&characterEncoding=UTF-8
        username: root
        password: root$%^
        driver-class-name: com.mysql.jdbc.Driver
        name: mysql

    jpa:
        show-sql: true
        generate-ddl: true
        ddl-auto: update

alipay:
    partner: 2088011310795
    key: nenf4q46f1de7cp98
    seller:
        email: zhangsan_001@duobei.com
    notify_url: http://www.duobeiyun.com/shop/alipay/payment/callback
    return_url: http://www.duobeiyun.com/shop